### ISSUE TITLE
猜头像提示错误

### ISSUE THREAD

**Issue by Sasa-kid** [GWYOG/HoshinoBotAdditionalPlugins#1]
发指令之后提示can only concatenate str (not "MessageSegment") to str   再发一次指令提示游戏已经开始了

**Comment by GWYOG** [comment]
我这边好像暂时无法复现这个bug..游戏卡住然后提示游戏已经开始目前只能重启bot解决，之后我会改的。
想问下这个bug是偶发的吗？以及你HoshinoBot的资源文件夹里有没有全角色头像的资源包?

**Comment by Sasa-kid** [comment]
![QQ截图20200817003739](https://user-images.githubusercontent.com/68634616/90339199-e47a8a00-e021-11ea-8f55-e0e4b4f32493.png)    全角色头像资源包是这个吗  发指令之后指令就会生成第一个的那个图片 但是不会发出来
![QQ图片20200817003956](https://user-images.githubusercontent.com/68634616/90339260-38856e80-e022-11ea-9b8f-d677c21ad6f1.png)

**Comment by Sasa-kid** [comment]
另外的那个小游戏是正常可以玩的，就这个有问题

**Comment by GWYOG** [comment]
收到，今晚我会再仔细看看。这个小游戏确实bug可能会稍微多一点...我写完后发现代码结构太差了，只要中间哪个环节报错整个插件就会卡死Orz(不过我自己测试时倒没出过问题)，准备有时间时重构下代码

**Comment by GWYOG** [comment]
好吧..我大概清楚哪有问题了，应该修好了，你试试。
不过很迷的一点是，我原来的写法在我这儿都不报错不知道为什么在你那儿就不行了。
我目前的测试环境和你一样用的也是xcw bot。

**Comment by Sasa-kid** [comment]
可以玩了，感谢
